from .usuario import Usuario
from .direccion import Direccion
from .transportista import Transportista
from .provincia import Provincia
from .localidad import Localidad
from .transportista_destino import TransportistaDestino
from .dias_reparto import DiaReparto
from .transportista_dia import TransportistaDia
from .codigo_postal import CodigoPostal
from .origen import Origen